### ISSUE TITLE
module 'tensorflow.tools.api.generator.api.math' has no attribute 'l2_normalize'

### ISSUE THREAD

**Issue by xahiru** [xiangwang1223/neural_graph_collaborative_filtering#18]
**I get the following error when I run the code:**
```
Traceback (most recent call last):
  File "NGCF.py", line 352, in <module>
    model = NGCF(data_config=config, pretrain_data=pretrain_data)
  File "NGCF.py", line 81, in __init__
    self.ua_embeddings, self.ia_embeddings = self._create_ngcf_embed()
  File "NGCF.py", line 219, in _create_ngcf_embed
    norm_embeddings = tf.math.l2_normalize(ego_embeddings, axis=1)
AttributeError: module 'tensorflow.tools.api.generator.api.math' has no attribute 'l2_normalize'
```

Do you think my TensorFlow installation is correct?

**steps**:
**creating the environment:**
```
conda create -n ngcf pytho
conda activate ngcf
conda install tensorflow==1.8.0
conda install numpy==1.14.3
conda install scipy==1.1.0
conda install scikit-learn==0.19.1
```
**clone n run:**
```
git clone https://github.com/xiangwang1223/neural_graph_collaborative_filtering.git
cd neural_graph_collaborative_filtering/NGCF/
python NGCF.py --dataset gowalla --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0001 --save_flag 1 --pretrain 0 --batch_size 1024 --epoch 400 --verbose 1 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]
```

**Environment:**
CentOS Linux release 7.5.1804 (Core)
conda 4.6.12
python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
scikit-learn 0.19.1
numpy        1.14.3
tensorflow   1.8.0

here's my attempt to debug in python prompt:
```
>>> import tensorflow as tf
>>> print(tf.__version__)
1.8.0
>>> print(dir(tf.math))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'polyval']
>>> print(dir(tf.math.l2_normalize))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.tools.api.generator.api.math' has no attribute 'l2_normalize'

```
for me, it seems like the module is no there in this version of TensorFlow. I'll update TensorFlow n see if works.

**Comment by xahiru** [comment]
There's a type in step 1, I missed '_n_' in '_python_' it while I was copying the commands, not the cause of the error. so it should be
`conda create -n ngcf python`

**Comment by xahiru** [comment]
hi,
after updating TensorFlow, it worked :-)
bt still gets a bunch of warning.

**Comment by xuzhang5788** [comment]
change 
tf.math.l2_normalize(.....)
into
tf.nn.l2_normalize(.....)

it works for me. 
tensorflow 1.10.0
